### ISSUE TITLE
Suggested change for GLFusion External Pages Plugin

### ISSUE THREAD

**Issue by mlapl1** [leegarner-glfusion/external#2]
Hi Lee,

When an external page is called for the first time, the user that runs the page becomes the owner of the external page registration - thus getting read-write access.

I suggest therefore to add an owner field/dropdown box to the default settings area of the plugin in the same way that a group dropdown box exists.

Thanks

**Comment by leegarner** [comment]
It's been so long since I looked at that I don't even remember if there was
a good reason to have permissions. I'll check and see.

**Comment by mlapl1** [comment]
Hi Lee - thanks for responding. Actually, it is working really well and the
default permissions are really valuable. No need to touch them. It's just
the question of the default owner who is set essentially by chance.

Thanks
Andrew

## 

Professor Dr. Andrew Lian, Suranaree University of Technology
Emeritus Professor, University of Canberra, Canberra, ACT, Australia
President of AsiaCALL
School of Foreign Languages
Institute of Social Technology
Suranaree University of Technology
111 University Avenue
Muang District
Nakhon Ratchasima, Thailand, 30000
e-mail: andrew.lian@andrewlian.com; website: http://gocultures.com/apl
(new) http://www.andrewlian.com

We don't see things as they are, we see things as we are. (Anaïs Nin)
"We reify the limits of our perception and call it reality" -- Donald
Hoffman, UC Irvine
The universe is made up of stories, not atoms (Muriel Rukeyser)
Change the way you look at things and the things you look at change (Max
Planck)
Science progresses one funeral at a time (Max Planck)

**Comment by leegarner** [comment]
This has been resolved and will be updated in v 1.0.2
